[package]
name = "neon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
bytemuck = "1.22.0"
env_logger = "0.11.6"
image = "0.25.5"
log = "0.4.26"
nalgebra = "0.33.2"
rand = "0.9.0"
rayon = "1.10.0"
rgb = "0.8.50"
typed-builder = "0.20.0"
